name: einundzwanzig_meetup_app
description: "Einundzwanzig Meetup App â€“ Badge-System mit NFC, QR & Nostr Web of Trust"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  url_launcher: ^6.2.5

  # Networking & Data
  http: ^1.6.0
  shared_preferences: ^2.5.4
  icalendar_parser: ^2.0.0

  # NFC
  nfc_manager: ^4.1.1
  nfc_manager_ndef: ^1.0.1

  # Crypto & Nostr
  crypto: ^3.0.6
  dbcrypt: ^2.0.0
  nostr: ^1.5.0

  # Backup & Sharing
  share_plus: ^10.1.4
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
